export const prepareFilters = (filters) => ({
    board: filters.board && filters.board !== 0 ? [filters.board] : null,
    bust: filters.body?.bust,
    cupSize: filters.body?.cupSize,
    dressSize: filters.body?.dressSize,
    eyeColor: filters.body?.eyeColor,
    genders: filters.genders,
    hairColor: filters.body?.hairColor,
    hairLength: filters.body?.hairLength,
    height: filters.body?.height,
    hips: filters.body?.hips,
    managers: filters.managers,
    noContacts: filters.noContacts,
    preferences: filters.preferences,
    shirtSize: filters.body?.shirtSize,
    shoeSize: filters.body?.shoeSize,
    skinColor: filters.body?.skinColor,
    suitCut: filters.body?.suitCut,
    waist: filters.body?.waist,
    weight: filters.body?.weight,
});
